# Warning: local config will not be updated automatically and may break new app
# versions in the future.
#
# All supported configuration can be found at
# https://github.com/mindaugasw/timestamp-statusbar-converter/blob/master/config.yml
#
# After editing configuration the application must be restarted.
