; See `mypy.md` for my own documentation/cheatsheet

[mypy]
warn_unused_ignores = True
show_error_code_links = True
; pretty - show code snippets in command output
pretty = True
cache_dir = var/mypy_cache
; native_parser improves performance a tiny bit (3.8s => 3.6s)
native_parser = True

; See mypy.md for exclude docs
;exclude = (?x)(
;    chartsTutorial\.py  # This is a comment
;  )

[mypy-AppKit.*]
; Ignoring because there are no type stubs
ignore_missing_imports = True

[mypy-dearpygui.*]
; Ignoring because there are no type stubs
ignore_missing_imports = True

[mypy-dearpygui_ext.*]
ignore_missing_imports = True

[mypy-rumps.*]
; Ignoring because it's installable only on macOS
ignore_missing_imports = True

[mypy-gi.*]
; Causes error: "gi.repository" module is installed, but missing library stubs or py.typed marker
follow_untyped_imports = True
