# If enabled, text in the statusbar will be cleared after copying anything else
clear_on_change: false

# Automatically clear text in the status bar after this time, in seconds.
# 0 to disable automatic clearing.
clear_after_time: 300

# If enabled, will shortly flash status bar icon on timestamp change
flash_icon_on_change: true

# If enabled, will log additional info when running from the terminal.
# Alternatively, can be enabled with --debug option when running from the command line.
debug: false

converters:
    distance:
        enabled: true
        primary_unit_metric: true

    temperature:
        enabled: true
        primary_unit: C

    timestamp:
        enabled: true

        # Formatting template for text on the statusbar.
        #
        # Used template will be the first one, where relative time difference in
        # seconds is less than the key number
        #
        # Templates must be ordered ascending by time difference by their key.
        #
        # Templates support all standard strftime() codes:
        # https://docs.python.org/3/library/datetime.html#strftime-and-strptime-format-codes
        # and these custom codes for relative time:
        # - {ts} - unix timestamp. Without milliseconds.
        # - {ts_ms} - unix timestamp. With milliseconds, if millisecond timestamp was copied.
        #             Without milliseconds otherwise.
        #             Can be used to copy a valid millisecond timestamp.
        # - {ts_ms_sep} - unix timestamp. With milliseconds, separated by a dot, if millisecond
        #                 timestamp was copied. Without milliseconds otherwise.
        #                 Can be used for easier readability.
        # - {r_int} - relative time with integer number, e.g. '5 h ago'.
        # - {r_float} - relative time with float number, e.g. '5.5 h ago'.
        icon_text_format:
            # Up to 60 s, e.g. "1619295908 - 59 s ago"
            60: "{ts_ms_sep} - {r_int}"
            # Up to 10 min, e.g. "1619295908 - 5 min ago"
            600: "{ts_ms_sep} - {r_int}"
            # Up to 1 hour, e.g. "1619295908 - 29 min ago (15:10)"
            3600: "{ts_ms_sep} - {r_float} (%H:%M)"
            # TODO add more templates. E.g. Show float hours (5.5) only up to like 6 hours. Afterwards show int number
            # Up to 1 day, e.g. "1619295908 - 5.5 h ago (12:00)"
            86400: "{ts_ms_sep} - {r_float} (%H:%M)"
            # Up to 1 month, e.g. "1619295908 - 5.5 days ago (08-05 12:00)"
            2678400: "{ts_ms_sep} - {r_float} (%m-%d  %H:%M)"
            # Up to 1 year, e.g. "1619295908 - 9.2 months ago"
            31536000: "{ts_ms_sep} - {r_float} (%m-%d  %H:%M)"
            # Up to 75 years, e.g. "1619295908 - 5.8 years ago ('15)"
            2365200000: "{ts_ms_sep} - {r_float} ('%y)"
            # Default if no other format matches. Must be last element in the list
            default: "{ts_ms_sep} - {r_float}"

        # Menu items to create under "Last conversion" category. Text copied on click.
        # Supports the same formats as in "icon_text_format".
        menu_items_last_conversion:
            original_text: "{ts_ms}"
            converted_text: "%Y-%m-%d %H:%M:%S"

        # Menu items to create under "Current timestamp" category.
        # Supports the same formats as in "icon_text_format".
        menu_items_current_timestamp:
            # Label text: "format to copy on click"
            Current timestamp: "{ts}"
            Current datetime: "%Y-%m-%d %H:%M:%S"
