# Warning: user config will not be updated automatically and may break new app
# versions in the future.
#
# All supported configuration can be found at
# https://github.com/mindaugasw/statusbar-converter/tree/master/config/config.app.yml
#
# After editing configuration the application must be restarted.
