# If enabled, will log more verbose info.
# Alternatively, can be enabled with --debug option when running from the command line.
debug: false

converters:
    timestamp:
        # Formatting template for text on the statusbar.
        #
        # Configuration format:
        # - key: maximum number of seconds until which this template will be used.
        #        Selected template will be the first one matching (where time
        #        difference in seconds is less than key number), so templates must
        #        be ordered ascending by key.
        # - value: displayed format. See below for supported formatting.
        #
        # Supported formatting:
        # All standard strftime() codes: https://docs.python.org/3/library/datetime.html#strftime-and-strptime-format-codes
        # and these custom codes for relative time:
        # - {ts} - unix timestamp. Without milliseconds.
        # - {ts_ms} - unix timestamp. With milliseconds, if millisecond timestamp was copied.
        #             Without milliseconds otherwise.
        #             Can be used to copy a valid millisecond timestamp into clipboard.
        # - {ts_ms_sep} - unix timestamp. With milliseconds, separated by a dot, if millisecond
        #                 timestamp was copied. Without milliseconds otherwise.
        #                 Can be used for easier readability.
        # - {r_int} - relative time with integer number, e.g. '5 h ago'.
        # - {r_float} - relative time with float number, e.g. '5.5 h ago'.
        icon_text_format:
            # Up to 60 s, e.g. "1619295908 - 59 s ago"
            60: "{ts_ms_sep} - {r_int}"
            # Up to 10 min, e.g. "1619295908 - 5 min ago"
            600: "{ts_ms_sep} - {r_int}"
            # Up to 1 hour, e.g. "1619295908 - 29 min ago (15:10)"
            3600: "{ts_ms_sep} - {r_int} (%H:%M)"
            # Up to 5 hours, e.g. "1619295908 - 4.5 h ago (12:00)"
            18000: "{ts_ms_sep} - {r_float} (%H:%M)"
            # Up to 1 day, e.g. "1619295908 - 8 h ago (12:00)"
            86400: "{ts_ms_sep} - {r_int} (%H:%M)"
            # Up to 3 days, e.g. "1619295908 - 2.5 days ago (08-05 12:00)"
            259200: "{ts_ms_sep} - {r_float} (%m-%d  %H:%M)"
            # Up to 1 month, e.g. "1619295908 - 7 days ago (08-05 12:00)"
            2678400: "{ts_ms_sep} - {r_int} (%m-%d  %H:%M)"
            # Up to 3 months, e.g. "1619295908 - 2.5 months ago"
            7879680: "{ts_ms_sep} - {r_float} (%m-%d  %H:%M)"
            # Up to 1 year, e.g. "1619295908 - 9 months ago"
            31536000: "{ts_ms_sep} - {r_int} (%m-%d  %H:%M)"
            # Up to 10 years, e.g. "1619295908 - 2.5 years ago ('15)"
            315360000: "{ts_ms_sep} - {r_float} ('%y)"
            # Up to 75 years, e.g. "1619295908 - 13 years ago ('15)"
            2365200000: "{ts_ms_sep} - {r_int} ('%y)"
            # Default if no other format matches. Must be last element in the list
            default: "{ts_ms_sep} - {r_float}"

        # Menu items to create under "Last conversion" category. Text copied on click.
        # Supports the same formats as in "icon_text_format".
        menu_items_last_conversion:
            original_text: "{ts_ms}"
            converted_text: "%Y-%m-%d %H:%M:%S"

        # Menu items to create under "Current timestamp" category.
        # Supports the same formats as in "icon_text_format".
        menu_items_current_timestamp:
            # Key is value to show in the UI
            # Value is value to copy into clipboard
            Current timestamp: "{ts}"
            Current datetime: "%Y-%m-%d %H:%M:%S"
